-- CreateTable
CREATE TABLE `WasteCategory` (
    `UUID_WC` VARCHAR(191) NOT NULL,
    `Title_WC` VARCHAR(191) NOT NULL,
    `Description_WC` TEXT NOT NULL,
    `Image_WC` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`UUID_WC`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
