-- CreateTable
CREATE TABLE `ArticleData` (
    `UUID_AD` VARCHAR(191) NOT NULL,
    `Title_AD` VARCHAR(191) NOT NULL,
    `Description_AD` VARCHAR(191) NOT NULL,
    `Image_AD` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`UUID_AD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
