-- DropIndex
DROP INDEX `VoucherUser_UUID_UD_key` ON `VoucherUser`;

-- AddForeignKey
ALTER TABLE `VoucherUser` ADD CONSTRAINT `VoucherUser_UUID_UD_fkey` FOREIGN KEY (`UUID_UD`) REFERENCES `UserData`(`UUID_UD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `VoucherUser` ADD CONSTRAINT `VoucherUser_UUID_VD_fkey` FOREIGN KEY (`UUID_VD`) REFERENCES `VoucherData`(`UUID_VD`) ON DELETE RESTRICT ON UPDATE CASCADE;
